name: shader_presets
description: "Shader presets using shader_buffers"
version: 1.0.0
homepage:

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  shader_buffers:
    path: ../shader_buffers

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0


flutter:

  shaders:
    - assets/shaders/shadertoy/water.frag
    - assets/shaders/shadertoy/page_curl.frag
    - assets/shaders/shadertoy/barrel.frag

    - assets/shaders/gl_transitions/cube.frag
    - assets/shaders/gl_transitions/polka_dots_curtain.frag
    - assets/shaders/gl_transitions/radial.frag
    - assets/shaders/gl_transitions/flyeye.frag